# Generated by Django 5.1.7 on 2025-03-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transportation', models.ManyToManyField(to='orders.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_departure', models.DateField()),
                ('date_return', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('report_to', models.CharField(max_length=200)),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.travelorder')),
            ],
        ),
    ]
