# Generated by Django 5.1.7 on 2025-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='transportation',
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='transportation',
            field=models.ManyToManyField(to='orders.transportation'),
        ),
    ]
