# Generated by Django 5.1.7 on 2025-04-21 05:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
