# Generated by Django 5.1.7 on 2025-04-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_from', models.DateField()),
                ('service_to', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_of_assignment', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('lwop', models.CharField(blank=True, max_length=100, null=True)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('separation_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='service_order.serviceorder')),
            ],
        ),
    ]
